### ISSUE TITLE
Manipulando arrays em PHP utilizando funções

### ISSUE THREAD

**Issue by adrieleribeiro** [PHPRio/CFP#100]
Título: **Manipulando arrays em PHP utilizando funções**
Palavras-chaves: `php`, `array`, `function`, `iniciante`, `ordenação`, `vetor`
Nível: **básico**
Palestrante: [**Adriele Ribeiro**](99)

Descrição da palestra:
> Nesta palestra você conhecerá funções do PHP que permitem realizar operações com arrays de forma eficiente e rápida.

**Comment by vitormattos** [comment]
Palestra apresentada no meetup que segue:
https://www.meetup.com/PHP-Rio/events/tgljxpyzhbfc/
