### ISSUE TITLE
Power Presentations: Venda suas ideias

### ISSUE THREAD

**Issue by Kleber4157** [PHPRio/CFP#113]
Título: **Título descritivo e interessante**
Palavras-chaves: `Falar em Público`, `Apresentar projetos`, `Vender Ideias`
Nível: **básico**
Palestrante: [**Kleber Rodrigues**](115)
Descrição da palestra:
> Cada vez mais os profissionais de tecnologia tem de sair da frente do computador e vender seus projetos e suas ideias para públicos variados. Falar em público pode ser assustador para muitos, mas é uma necessidade! Então...: Aprenda dicas rápidas para criar apresentações poderosas!

**Comment by DaianeAlvesRJ** [comment]
Palestra apresentada em 23/08/2019
Link para o evento: https://www.meetup.com/pt-BR/PHP-Rio/events/tgljxpyzlbdc/
