### ISSUE TITLE
PHPCurl e coleta de dados na Web

### ISSUE THREAD

**Issue by lga37** [PHPRio/CFP#116]
Título: **PHPCurl e coleta de dados na Web**
Palavras-chaves: `curl`, `multi-curl`, `login`, `captcha`, `regex`, `dom`
Nível: **intermediário**
Palestrante: **Gustavo Almeida**
Descrição da palestra:
> Palestra falando sobre o componente nativo do PHP usado principalmente para coletar diversos tipos de dados da web através de robôs de busca.

**Comment by vitormattos** [comment]
Pode apresentar dia 23 deste mês?

**Comment by DaianeAlvesRJ** [comment]
Palestra apresentada no evento do dia 23/10/2019
Link para o evento: https://www.meetup.com/pt-BR/PHP-Rio/events/tgljxpyznbgc/
