### ISSUE TITLE
Contribuindo e criando software livre

### ISSUE THREAD

**Issue by vitormattos** [PHPRio/CFP#12]
# Descritivo
Após esta palestra você certamente saberá como criar um projeto livre em PHP. Abordaremos diversas dicas como: PSR, diversos tipos de testes e ferramentas para testes, análise de sintaxe, como documentar um projeto de forma saudável evitando retrabalho, distribuição do seu software, como interagir com outros profissionais.

Existem milhares de desenvolvedores PHP pelo Brasil, também temos dezenas de comunidades PHP e de todas estas pessoas, quantas delas contribuem ou já contribuíram para algum projeto livre de alguma forma?
Mas enfim,  o que é software livre? Tem diferença entre software livre e open source? Como devo iniciar um projeto de software livre em PHP? Qual licença devo utilizar em meu projeto? Como garantir a qualidade do meu código?
São muitas perguntas a serem respondidas, nesta talk encontraremos luz

# Público alvo
Desenvolvedores em geral, de iniciantes a mais experientes. O único requisito é ter motivação em compartilhar conhecimento e dar retorno de alguma forma para comunidades de software livre.

**Comment by raphaeldealmeida** [comment]
Atividade aconteceu no dia 10/08/2017
https://www.meetup.com/pt-BR/PHP-Rio/events/241909710/
