### ISSUE TITLE
Mesa Redonda sobre Mulheres em TI

### ISSUE THREAD

**Issue by larismourullo** [PHPRio/CFP#19]
Pretende-se realizar uma mesa redonda sobre a participação das mulheres em TI, abordando diversos assuntos, alguns polêmicos outros não.

**Comment by dsouza1** [comment]
Ótimo, @larismourullo já tem uma data prevista?

**Comment by larismourullo** [comment]
@dsouza1 ao que tudo indica irá ocorrer dia 10 de agosto no próximo PHP Rio 💃

**Comment by raphaeldealmeida** [comment]
Atividade aconteceu no dia 10/08/2017
https://www.meetup.com/pt-BR/PHP-Rio/events/241909710/
