### ISSUE TITLE
Precisamos entregar valor e não tecnologia

### ISSUE THREAD

**Issue by gambarra** [PHPRio/CFP#25]
O foco da palestra é mostrar ao desenvolvedor que tecnologia tem que ser o meio para entregar um valor ao cliente. Por mais que nosso ego nos leve a sempre pensar em usar a tecnologia que esteja com maior relevância no momento, nossos clientes estão preocupados em ter seus problema de negócio sanado. E é isso que precisamos focar. Entregar valor e não tecnologia.

**Comment by raphaeldealmeida** [comment]
Palestra realizada no meetup de 28/09/2017 https://www.meetup.com/pt-BR/preview/PHP-Rio/events/242511850
