### ISSUE TITLE
You build it, you run it - Mantendo sua infraestrutura como parte da aplicação!

### ISSUE THREAD

**Issue by igordcsouza** [PHPRio/CFP#27]
# Descritivo
Muito se fala sobre desenvolvimento ágil, integração contínua e deploy contínuo para aplicações. Mas do que tudo isso adianta se a sua infraestrutura não tiver a capacidade de se transformar na mesma velocidade que a sua aplicação? E se sua equipe pudesse ser responsável por gerir sua própria infraestrutura, diretamente do repositório da sua aplicação, sem depender de tickets ou emails. Vamos ver como algumas ferramentas de DevOps podem empoderar os times de devs através da automação.

# Pré requisitos
Conhecimentos básicos de git.

# Público alvo
Desenvolvedores e Analistas de Infraestrutura que tenham curiosidade de como tratar toda sua infraestrutura como código, e assim automatizar sua criação. Não é necessário grande conhecimento em infraestrutura pois o objetivo é focar mais no conceito de como resolver esse problema do que em ferramentas.

# Slides

**Comment by raphaeldealmeida** [comment]
Proposta interessante, enfrentamos problemas para montar e alterar intra quase sempre.

**Comment by raphaeldealmeida** [comment]
Palestra realizada https://www.meetup.com/pt-BR/PHP-Rio/events/244670299/
