### ISSUE TITLE
Engenharia Social Surpreenda-se!

### ISSUE THREAD

**Issue by ghost** [PHPRio/CFP#28]
O que é ? Quais as ferramentas usadas?

**Comment by M4g43n0ch** [comment]
As pessoas procuram especular mas nem sabem que existem ferramentas para isso nem sabem como são atingidas com engenharia social.

**Comment by M4g43n0ch** [comment]
Acredito que é importante refletir e aprender mais sobre esse universo dos hackers e da engenharia social.

**Comment by raphaeldealmeida** [comment]
Não sei se entendi muito bem, adoro o assunto de hacking em redes sociais mas não conheço.
Pode dar mais detalhes?

**Comment by M4g43n0ch** [comment]
Existem muitas formas de se desenvolver engenharia social pelas redes sociais, desde um simples Footprinting até níveis mais elaborados de Engenharia Social. A captação de informações vantajosas a troca ou a influências de pessoas para benefício de algum objetivo final é o que faz das formas de Engenharia Social uma espécie de arma da atualidade tão importante quanto a manipulação da massa pela mídia.

**Comment by M4g43n0ch** [comment]
É bem comum recebermos pushing para não só fazerem mídia mas para a captação dos seus dados, é um meio de acesso bem comum. A maior falha de segurança é o fator humano. Uma simples pagina fake já é o suficiente para que o usuário se torne porta de entrada da sua própria empresa para pessoas má intencionadas. São exemplos comuns, mas as pessoas surpreendentemente ainda são vítimas disso.
