### ISSUE TITLE
Explorando Segurança e trabalhando PHP

### ISSUE THREAD

**Issue by ghost** [PHPRio/CFP#29]
Acredito que vai ser perfeito trabalhar ambas as coisas juntas mostrando a questão de gestão de qualidade de software que também gera vulnerabilidades a serem exploradas. Logo, a salvação! Segurança da informação. Vamos aprender, vamos informar, vamos crescer!

**Comment by raphaeldealmeida** [comment]
Segurança é um assunto gigante, e pode ser abordado de várias maneiras desde o básico de como sanitarizar entradas a coisas mais avançadas como a criação de [hashes com Argon2 no PHP 7.2](https://framework.zend.com/blog/2017-08-17-php72-argon2-hash-password.html) 

Quais seria a sua ideia de palestra?

**Comment by M4g43n0ch** [comment]
Você pode trabalhar segurança de diversas formas e eu tenho visto erros catastróficos derivados de códigos PHP entre outros que podem ser melhorados no próprio código. As pessoas procuram acreditar que tem que proteger a segurança, mas desenvolvem códigos que errados que possibilitam invasões em pequenas falhas. Como melhorar a segurança de software e como criar bons formulários e evitar brechas de segurança. Será que tendo segurança garantida do sistema com softwares prontos é o suficiente? As empresas sempre desenvolvem softwares sem um gestor de segurança de software e este vem cheio de furos.

**Comment by M4g43n0ch** [comment]
Acredito que um código bem elaborado quando se trata de segurança pode ser uma forma muito eficiente de se evitar grandes problemas. As empresas devem sim ter o gestor de segurança em seus projetos de software e de web a fim de melhorar não só o sistema mas as aplicações.

**Comment by M4g43n0ch** [comment]
Basicamente gestão de segurança de software aplicado ao dia a dia dor programador PHP. 
Pessoas erram em pequenos detalhes quando desenvolvem seus sitemas por apenas colocarem seu foco em produção e não em segurança.
