### ISSUE TITLE
Programação paralela com PHP - pthreads

### ISSUE THREAD

**Issue by CViniciusSDias** [PHPRio/CFP#32]
Título: Programação paralela com PHP - pthreads
Palavras-chaves: `pthreads`, `arquitetura`, `paralelismo`
Nível: Intermediário
Palestrante: [Vinicius Dias](https://github.com/PHPRio/CFP/issues/38)
Descrição da palestra:
> Introdução à programação paralela com PHP utilizando a extensão *pthreads*.
Ao contrário do que muitos podem pensar, o PHP é sim pronto para um ambiente multithreaded, e esta extensão traz ao usuário uma API fácil e amigável, para usufruir de threads de verdade (e não as famigeradas green threads).
Como pré-requisitos para aproveitar melhor esta palestra, é interessante ter conhecimentos básicos de PHP, Orientação a Objetos, e, preferencialmente, conhecimento de como funciona o mundo multithreaded.

GitHub: https://github.com/CViniciusSDias/exemplo-php-threads

**Comment by jeffotoni** [comment]
Troca o título para "Programação concorrente com PHP - pthreads",  programação concorrente é <> programação paralela

**Comment by vitormattos** [comment]
A proposta é workshop ou talk?

**Comment by CViniciusSDias** [comment]
Talk, @vitormattos

**Comment by CViniciusSDias** [comment]
Palestra apresentada no meetup de 27/09/2018:
https://www.meetup.com/pt-BR/PHP-Rio/events/tgljxpyxmbkc/
