### ISSUE TITLE
Jigsaw: sites estáticos e seguros para desenvolvedores ágeis.

### ISSUE THREAD

**Issue by DaianeAlvesRJ** [PHPRio/CFP#34]
# Descrição

Conheça um pouco mais sobre os geradores de sites estáticos que estão revolucionando a web e aprenda a construir um site estático utilizando PHP.

Jigsaw é um framework para a construção rápida de sites estáticos usando a mesma ferramenta moderna que já conhece para criação de aplicações web.

**Comment by vitormattos** [comment]
Palestra apresentada no [Meetup](https://www.meetup.com/PHP-Rio/events/247088858/) no dia 22/03/2018
