### ISSUE TITLE
Investigando a saúde do seu sistema através de logs

### ISSUE THREAD

**Issue by raphaeldealmeida** [PHPRio/CFP#44]
Título: **Investigando a saúde do seu sistema através de logs**
Palavras-chaves: `log`
Nível: **básico**
Palestrante: [**Raphael de Almeida**](43)
Descrição da palestra:
> Esta palestra apresenta cenários onde podemos identificar problemas com software em produção através de logs, estratégias do que “loggar” para futuras investigações, ferramentas de armazenamento, análise e ação de eventos de log.
Slides: https://speakerdeck.com/raphaeldealmeida/investigando-a-saude-do-seu-sistema-atraves-de-logs

**Comment by vitormattos** [comment]
Ae @merorafael e de pacote do Monolog?

**Comment by raphaeldealmeida** [comment]
Palestra apresentada no dia 21/11/2018
https://www.meetup.com/pt-BR/PHP-Rio/events/tgljxpyxpbdc/
