### ISSUE TITLE
Criação de API com Laravel

### ISSUE THREAD

**Issue by GabrielDeveloper** [PHPRio/CFP#45]
Título: **Criação de API com Laravel**
Palavras-chaves: `api`, `laravel`
Nível: **básico**
Palestrante: [**Gabriel Gonçalves**](https://github.com/PHPRio/CFP/issues/49)
Slides: https://www.slideshare.net/Gabriel-Goncalves/laravel-api
Descrição da palestra:
> Criação de uma api REST usando o framework Laravel, entendendo alguns conceitos da arquitetura do Laravel como Middlewares, Rotas etc..
 Criando testes para os endpoints da API usando Laravel.

**Comment by DaianeAlvesRJ** [comment]
Palestra apresentada no [Meetup](https://www.meetup.com/pt-BR/PHP-Rio/events/250099218/) do dia 24/05/2018.

**Comment by leogomezzz** [comment]
@GabrielDeveloper, pode compartilhar o código-fonte? Grato.

**Comment by GabrielDeveloper** [comment]
@leogomezzz , segue o repositorio:

https://github.com/GabrielDeveloper/palestra_laravel_api/tree/step2

O branch **step2** ta com a API completa.
