### ISSUE TITLE
GraphQL: PUTs, onde foram parar os verbos HTTP?

### ISSUE THREAD

**Issue by leogomezzz** [PHPRio/CFP#48]
Título: **GraphQL: PUTs, onde foram parar os verbos HTTP?**
Palavras-chaves: `Comunicação entre serviços`, `API`, `GraphQL`
Nível: **básico**
Palestrante: [**Leonardo Gomes da Silva**](https://github.com/PHPRio/CFP/issues/47)
Descrição da palestra:
> O que é GraphQL? Onde foram parar os verbos GET, PUT, DELETE, PATCH? E todos aqueles códigos de status HTTP que você não decorou, são realmente necessários? Juntos vamos conhecer essa linguagem open source, desenvolvida e utilizada pelo Zuckerberg, ou Mark para os íntimos.

Slides: [slideshare.net/leogomezzz1/graphql-puts-onde-foram-parar-os-verbos-http-98599421](https://www.slideshare.net/leogomezzz1/graphql-puts-onde-foram-parar-os-verbos-http-98599421)
Github: [github.com/leogomezzz/laravel-graphql](https://github.com/leogomezzz/laravel-graphql)

**Comment by DaianeAlvesRJ** [comment]
Palestra apresentada no [Meetup](https://www.meetup.com/pt-BR/PHP-Rio/events/250099218/) do dia 24/05/2018.
