### ISSUE TITLE
PHP OO, UML e Padrões, ou aprenda tudo ou aprenda nada!

### ISSUE THREAD

**Issue by andrePfeiffer** [PHPRio/CFP#51]
Aprenda como orientação a objetos, UML e padrões de projetos não são difíceis de aprender caso você entenda o papel de cada um. E você ainda ganha como bonus um mala de ferramentas para se comunicar melhor com seus colegas e com os clientes!

https://speakerdeck.com/pfeiffer/php-oo-uml-e-padroes-ou-aprenda-tudo-ou-aprenda-nada

**Comment by vitormattos** [comment]
Apresentada no meetup:
