### ISSUE TITLE
Grumphp - O que é, por que usar, por quê usar e como ele pode ajudar a deixar o código mais limpo

### ISSUE THREAD

**Issue by AnthonyMRodrigues** [PHPRio/CFP#53]
Título: **Grumphp - O que é, por que usar, por quê usar e como ele pode ajudar a deixar o código mais limpo**
Palavras-chaves: `PHP`, `clean code`, `PSR`, `Unit test`
Nível: **básico**
Palestrante: [**Anthony Matheus Rodrigues Conceição**](52)
Descrição da palestra:
> Essa é uma aprensentação mostrando um pouco do grumphp, uma dependência a ser instalada no seu projeto, para auxiliar nas boas práticas do projeto.

Slides: https://speakerdeck.com/anthonymrodrigues/grumphp ou https://docs.google.com/presentation/d/1S9z3SVVpiRfnu20tbyh2U7SrQnLZ6h6X87pmbSS6tTQ/edit?usp=sharing
GitHub: https://github.com/AnthonyMRodrigues/gerenciadorDeArquivos

**Comment by vitormattos** [comment]
Apresentada no meetup:

https://www.meetup.com/PHP-Rio/events/tgljxpyxkbjc/
