### ISSUE TITLE
OctoberCMS do zero a geração de api

### ISSUE THREAD

**Issue by Sosantos** [PHPRio/CFP#55]
Título: **OctoberCMS do zero a geração de api**
Palavras-chaves: `API`, `OctoberCMS`
Nível: básico
Palestrante: [Susana Santos](54)
Descrição da palestra:
> Introdução ao OctoberCMS, estrutura de pastas, o que é um plugin e um component. Exemplificação dos conceitos apresentados através da criação de uma api simples.

**Comment by vitormattos** [comment]
Apresentada no meetup:

https://www.meetup.com/PHP-Rio/events/tgljxpyxlbfc/
