### ISSUE TITLE
PHP com código limpo

### ISSUE THREAD

**Issue by andrePfeiffer** [PHPRio/CFP#59]
Título: **PHP com código limpo**
Nível: **básico**
Palestrante: [**André Pfeiffer**](58)
Descrição da palestra:
> Um guia prático de como fazer um código PHP mais limpo aumentando o valor não só do seu código mas como de você!

**Comment by vitormattos** [comment]
Dei uma atualizada no markdown.

**Comment by vitormattos** [comment]
Palestra apresentada no evento:

https://www.meetup.com/PHP-Rio/events/tgljxpyxpbdc/
