### ISSUE TITLE
Seja feliz com Drupal

### ISSUE THREAD

**Issue by andrePfeiffer** [PHPRio/CFP#60]
Título: **Seja feliz com Drupal**
Nível: **básico**
Palestrante: [**André Pfeiffer**](58)
Descrição da palestra:
> Como você pode ser feliz trabalhando com Drupal seja como site builder, designer ou developer. A idéia da palestra é apresentar o Drupal e como você pode começar a dominar ele!

**Comment by vitormattos** [comment]
Opa! Próximo meetup terá como tema CMS, rola de ser esta talk sua?

**Comment by vitormattos** [comment]
Apresentada no meetup:

https://www.meetup.com/PHP-Rio/events/tgljxpyxlbfc/
