### ISSUE TITLE
Tudo que você queria saber WordPress (e até o que não sabia que queria)

### ISSUE THREAD

**Issue by rdlmda** [PHPRio/CFP#62]
Título: **Tudo que você queria saber WordPress (e até o que não sabia que queria)**
Palavras-chaves: `CMS`, `WordPress`
Nível: **básico**
Palestrante: [**Rudá Almeida**](https://github.com/PHPRio/CFP/issues/61) 

Descrição da palestra:
> Uma apresentação do WordPress, o CMS que dá vida a praticamente um terço de toda a internet: 
> - Conheça a história desta plataforma e o que mudou nos 15 anos desde seu lançamento.
> - Tenha uma prévia das grandes mudanças que vêm por aí.
> - O mercado de trabalho em volta do WordPress.
> - Veja como é fácil criar um site em 5 minutos e poucos cliques.
> - Como expandir e modificar a aparência e funcionalidade do WordPress.
> - Descubra que não, WordPress não é só para blogs, dá pra fazer **muita** coisa com ele. 
> - Quer usar o WordPress como desenvolvedor ou como criador de conteúdo? Saiba como!
> - O que faz o WordPress ser o "queridinho" de tantos usuários e desenvolvedores?
> - WordPress não é seguro? Saiba como é possível combater hackers e malwares.

**Comment by vitormattos** [comment]
Apresentada no meetup:

https://www.meetup.com/PHP-Rio/events/tgljxpyxlbfc/
