### ISSUE TITLE
Clean code saves lives

### ISSUE THREAD

**Issue by andrePfeiffer** [PHPRio/CFP#66]
Título: **Clean code saves lives**
Palavras-chaves: `clean code`, `TDD`, `pair programming`, `refactoring`, `continuos integration`, `software quality`, `mamilos`
Nível: **básico**
Palestrante: [**André Pfeiffer**](58)
Descrição da palestra:
> Hoje escrever códigos ruins podem custar vidas e isso só vai agravar no futuro. Essa palestra tem como objetivo mostrar como os programadores podem tomar conta de seu futuro antes que uma inevitável catástrofe transforme a programação em um ambiente altamente regulamentado e hostil

**Comment by DaianeAlvesRJ** [comment]
Palestra apresentada no dia 21/11.
https://www.meetup.com/pt-BR/PHP-Rio/events/tgljxpyxpbdc/
