### ISSUE TITLE
Porque o PostgreSQL é o melhor Banco de Dados Objeto/Relacional para usar com o PHP

### ISSUE THREAD

**Issue by chiessilmb** [PHPRio/CFP#74]
Título: Porque o PostgreSQL é o melhor Banco de Dados Objeto/Relacional para usar com o PHP.

Palavras-chaves: `postgresql`, `databases`, `banco de dados`
Nível: **básico**
Palestrante: [Lucio Mario Bruni Chiessi](#73)

Descrição da palestra:
> Palestra com o objetivo de mostrar a todos os recursos mais poderosos, e talvez desconhecido por muitos, que o PostgreSQL possuí e que podem facilitar muito o trabalho do programador, trazendo desempenho, segurança e confiabilidade nos seus Aplicativos.    Temos a certeza que esta palestra irá causar surpresa em muitos dos que estiverem assistindo.

Slides: 
Vídeo: 
GitHub:

**Comment by chiessilmb** [comment]
Aquivo PDF da minha palestra:

[VORio.PHP Rio.PostgreSQL.(21-02-2019).pdf](https://github.com/PHPRio/CFP/files/2890356/VORio.PHP.Rio.PostgreSQL.21-02-2019.pdf)

**Comment by raphaeldealmeida** [comment]
Excelente apresentação, o palestrante demonstrou domínio no assunto e fez comparações extremamente pertinentes para o público desenvolvedor PHP. Eu trabalho mais com Oracle e MySQL fiquei com vontade de comprar na prática. Que venham as próximas partes

**Comment by vitormattos** [comment]
Exelente apresentação, parabéns pelo conteúdo! Uma aula de banco de dados como nunca vi antes!

**Comment by vitormattos** [comment]
Palestra apresentada no evento:

https://www.meetup.com/PHP-Rio/events/tgljxpyzdblc/
