### ISSUE TITLE
PHPStan - A sincera cobertura para seu sistema

### ISSUE THREAD

**Issue by calexandrepcjr** [PHPRio/CFP#79]
Título: PHPStan - A sincera cobertura para seu sistema
Palavras-chaves: PHPStan, Lint, Code Quality, Testing
Nível: **básico**
Palestrante: [Carlos Alexandre](https://github.com/PHPRio/CFP/issues/78)
Descrição da palestra:
PHPStan é um lint poderoso que ajuda no coverage de aplicações PHP. A partir desta apresentação mostrarei sobre linters, sua utilização, exemplos e um case real de utilização em um produto.

**Comment by calexandrepcjr** [comment]
Segue apresentação https://capcj.gitlab.io/presentations/

**Comment by vitormattos** [comment]
Palestra apresentada no evento:

https://www.meetup.com/PHP-Rio/events/tgljxpyzdblc/

**Comment by vitormattos** [comment]
Parabéns, ótima talk! Espero poder vê-la novamente
