### ISSUE TITLE
O que é gestão do conhecimento e o que a Wikipedia tem a ver com isso?

### ISSUE THREAD

**Issue by tarcilas** [PHPRio/CFP#81]
Título: **O que é gestão do conhecimento e o que a Wikipedia tem a ver com isso?**
Palavras-chaves: `knowledge management`, `wiki`, `mediawiki`
Nível: **básico**
Palestrante: [**Tarcila Silva**](80)
Descrição da palestra:
> Entenda o que é gestão do conhecimento e qual a sua importância para empresas no contexto atual de excesso de informação e rotatividade de pessoas. Conheça também a MediaWiki, uma ferramenta free e open source, desenvolvida com PHP, que pode auxiliar no processo de gestão do conhecimento.

**Comment by vitormattos** [comment]
Palestra apresentada no meetup:

https://www.meetup.com/PHP-Rio/events/tgljxpyzfblc/
