### ISSUE TITLE
Principais processos de criação de um Banco de Dados e comuns erros de aplicação e segurança

### ISSUE THREAD

**Issue by pcoutinhoo** [PHPRio/CFP#82]
Título: **Principais processos de criação de um Banco de Dados e comuns erros de aplicação e segurança**
Palavras-chaves: `segurança`, `Banco `, `Dados `
Nível: Básico
Palestrante: [**Perla Coutinho**](https://github.com/PHPRio/CFP/issues/83)
Descrição da palestra:
> A palestra em questão abordará um pouco sobre os processos de criação de um banco de dados que mantenha a integridade dos dados eliminando erros de integridade no sistema, e assim oferecendo um bom desempenho e informações consistente. Os erros mais comuns de administração também serão abordados, como também a importância de segurança das suas aplicações.

**Comment by vitormattos** [comment]
Palestra apresentada no meetup:

https://www.meetup.com/PHP-Rio/events/tgljxpyzfblc/
