### ISSUE TITLE
Comunidades de TI: O outro lado da moeda

### ISSUE THREAD

**Issue by gaby-andrade** [PHPRio/CFP#85]
Título: **Comunidades de TI: O outro lado da moeda**
Palavras-chaves: `carreira`, `comunidade`, `tecnologia`
Nível: **básico**
Palestrante: [**Gabrielly de Andrade**](https://github.com/PHPRio/CFP/issues/84)
Descrição da palestra:
> Saiba da importância de participar de comunidades não só como expectador, mas também como organizador e produtor de conteúdo. Entenda "o outro lado da moeda" ao participar de um evento como coordenador e os benefícios que podem trazer pessoalmente e profissionalmente. Nesta palestra irei compartilhar minha experiência como líder local do RJ da comunidade feminina [WomakersCode](http://womakerscode.org/) e como comecei organizando. No final teremos um espaço para discussão, onde compartilharemos experiências e ideias.

**Comment by vitormattos** [comment]
Palestra apresentada no meetup:

https://www.meetup.com/PHP-Rio/events/tgljxpyzfblc/
