### ISSUE TITLE
Working with legacy code: lessons learnt from other people's knowledge, thoughts and ideas

### ISSUE THREAD

**Issue by rcapp** [PHPRio/CFP#87]
Título: **Working with legacy code: lessons learnt from other people's knowledge, thoughts and ideas.**
Palavras-chaves: `experiência`, `código`, `arquitetura`
Nível: **intermediário**
Palestrante: [**Ricardo Cappellano**](86)
Descrição da palestra:
> Most of the time the development process involves working on legacy code and systems. The term “legacy” is usually put in a negative context and perspective, referring to poor code, bad practices and broken process and infrastructure. However, this is not always the case and legacy systems are there, most of the time, delivering value and making money. On this talk, we will try to briefly cover what is a legacy code and some strategies that can be adopted to work on them.

**Comment by vitormattos** [comment]
Palestra apresentada no meetup:
https://www.meetup.com/PHP-Rio/events/tgljxpyzgbhc/
