### ISSUE TITLE
My life as a PHP software developer at MeuPatrocinio

### ISSUE THREAD

**Issue by calexandrepcjr** [PHPRio/CFP#88]
Título: My life as a PHP software developer at MeuPatrocinio
Palavras-chaves: `case`, `software engineering`, `slice-of-life`
Nível: **básico**
Palestrante: [Carlos Alexandre](https://github.com/PHPRio/CFP/issues/78)
Descrição da palestra:
> When I started in the IT field, I always found curious about developers talking about their career, quirks, cases inside the company and stuff. In this presentation, I will show a glimpse of my work, the product I'm working on, what are my current challenges and what I did to improve the system while implementing new features almost daily. It's more about a brief overview into daily life of a software developer.

https://capcj.gitlab.io/presentations/content/mylifeatmp.html#/

**Comment by vitormattos** [comment]
Palestra apresentada no meetup:
https://www.meetup.com/PHP-Rio/events/tgljxpyzgbhc/
