### ISSUE TITLE
Saving projects with awesome PHP

### ISSUE THREAD

**Issue by henriqueramos** [PHPRio/CFP#91]
Título: Saving projects with awesome PHP
Palavras-chaves: `legacy projects`, `awesome php`, `small frameworks`, `mini frameworks`
Nível: **básico**
Palestrante: [**Henrique Ramos**](https://github.com/PHPRio/CFP/issues/90)
Descrição da palestra:
> A small presentation about how you can save projects (and the world) with awesome PHP.

**Comment by vitormattos** [comment]
Palestra apresentada no meetup que segue:
https://www.meetup.com/PHP-Rio/events/tgljxpyzgbhc/
