### ISSUE TITLE
Conversão de mídia com FFmpeg e shell_exec

### ISSUE THREAD

**Issue by milacerda** [PHPRio/CFP#95]
Título: **Conversão de mídia com FFmpeg e `shell_exec`**
Palavras-chaves: `Palestras`, `iniciante`
Nível: **básico**
Palestrante: [Camila Lacerda](94)
Descrição da palestra:
> Veja como converter áudio e vídeo com poucos comandos utilizando FFmpeg e o poder do shell_exec.

Referências:
* https://trac.ffmpeg.org/wiki/PHP
* https://php.net/shell_exec

**Slides:** https://docs.google.com/presentation/d/1Z5D6CV6qqe2jdb1otqa3mBEXihaOt78IW6EAFx_q6wI/edit?usp=sharing

**Comment by vitormattos** [comment]
Palestra apresentada no meetup que segue:
https://www.meetup.com/PHP-Rio/events/tgljxpyzhbfc/
