### ISSUE TITLE
Reinventar a roda pode te fazer evoluir

### ISSUE THREAD

**Issue by romulowspp** [PHPRio/CFP#97]
Título: **Reinventar a roda pode te fazer evoluir**
Palavras-chaves: `padrões de projeto`, `POO`, `arquitetura de software`
Nível: **básico**
Palestrante: [**Romulo Pires**](96)
Descrição da palestra:
> Muitas vezes optamos por usar coisas prontas com o argumento de que não devemos reinventar a roda, muitas vezes por falta de tempo ou mesmo por querer sempre usar coisas consolidadas pela comunidade, até mesmo por pressão de outras pessoas.
Nessa palestra vou mostrar como reinventar a roda pode ser muito bom para você evoluir como programador e realmente saber como as coisas funcionam, que em muito dos casos é o diferencial para a resolução de um grande problema. Mostrarei um caso que aconteceu comigo para exemplificar o quanto eu aprendi e como fiquei surpreso que o resultado final ficou parecido e em alguns aspectos melhor que o projeto que já existia.

**Comment by vitormattos** [comment]
Palestra apresentada no meetup que segue:
https://www.meetup.com/PHP-Rio/events/tgljxpyzhbfc/
