### ISSUE TITLE
PDO: Trabalhando com banco do jeito certo

### ISSUE THREAD

**Issue by pcoutinhoo** [PHPRio/CFP#98]
Título: **PDO: Trabalhando com banco do jeito certo**
Palavras-chaves: `PDO`, `BANCO DE DADOS`
Nível: **Iniciante**
Palestrante: [Perla Coutinho](83)

Descrição da palestra:
> Nesta palestra falarei sobre a extensão PHP Data Objects ( PDO ), que define uma interface leve e consistente para gerenciar conexões com bancos de dados, ou seja, é possível usar PDO para conectar com diversos SGBDs, dentre eles MySQL, PostreSQL, SQLite, MS SQL Server, Oracle e outros. Porém, muitos programadores ainda não sabem como usar, então vou mostrar nesta palestra como é simples usar essa classe.

**Comment by vitormattos** [comment]
Palestra apresentada no meetup que segue:
https://www.meetup.com/PHP-Rio/events/tgljxpyzhbfc/
